const cryptography = {
  id: "cryptography",
  title: "Cryptography",
  description: "Cryptographic protocols, attacks, and constructions.",
  basePath: "/modules/cryptography",
  notes: [
    {
      id: 1,
      name: "Birthday_paradox",
      title: "Birthday Paradox",
      category: "Hash Functions",
      file: "Birthday_paradox.pdf",
      description: "Explores the birthday paradox and its implications for hash collision probability.",
      content: [
        "The birthday paradox states that far fewer people",
        "than expected are needed for a high probability of",
        "two sharing a birthday. With only 23 people there is",
        "already a >50% chance of a match from 365 dates.",
        "This follows from the pigeonhole principle; the",
        "paradox concerns probability, not impossibility.",
        "",
        "Birthday attacks apply this to hash functions and",
        "target collision resistance. Hash functions produce a",
        "fixed-size digest regardless of input size, so",
        "different messages can hash to the same value.",
        "",
        "An attacker exploits the birthday bound: finding a",
        "collision requires only ~2^(n/2) attempts for an",
        "n-bit hash, rather than the expected 2^n.",
        "The digest size must therefore be large enough to",
        "make this statistically infeasible.",
        "",
        "SHA-256 offers only 128-bit collision resistance",
        "despite its 256-bit output. Designers must account",
        "for this square-root relationship when choosing",
        "hash output lengths.",
      ],
    },
    {
      id: 2,
      name: "Diffie_Hellman_example",
      title: "Diffie-Hellman Key Exchange Example",
      category: "Key Exchange",
      file: "Diffie_Hellman_example.pdf",
      description: "Worked example of the Diffie-Hellman key exchange protocol.",
      content: [
        "Worked example of Diffie-Hellman key exchange.",
        "Setup: Alice (x=3), Bob (y=5),",
        "public params n=11, g=7.",
        "",
        "Alice computes A = g^x mod n = 7^3 mod 11 = 2",
        "  -> sends A=2 to Bob.",
        "Bob computes B = g^y mod n = 7^5 mod 11 = 10",
        "  -> sends B=10 to Alice.",
        "",
        "Shared secret derivation:",
        "  Alice: B^x mod n = 10^3 mod 11 = 10  (K=10)",
        "  Bob:   A^y mod n = 2^5  mod 11 = 10  (K=10)",
        "Both arrive at the same shared key K=10.",
        "",
        "Pohlig-Hellman attack works well on small prime",
        "subgroups. Use a safe prime where (p-1)/2 is",
        "also prime to defend against this.",
      ],
    },
    {
      id: 3,
      name: "ECDH_example",
      title: "Elliptic Curve Diffie-Hellman Example",
      category: "Key Exchange",
      file: "ECDH_example.pdf",
      description: "Worked example of ECDH key exchange using elliptic curve cryptography.",
      content: [
        "ECDH uses an elliptic curve E, its order #E,",
        "and a generator point G.",
        "",
        "Alice picks a in {1,2..#E-1},",
        "Bob picks b in {1,2..#E-1}.",
        "Alice sends A = aG to Bob.",
        "Bob sends B = bG to Alice.",
        "Shared key: k_ab = aB = bA (both equal abG).",
        "",
        "Point compression:",
        "  For every x there are 2 possible y values.",
        "  No need to transmit the full (x, y) point.",
        "  y = sqrt(x^3 + 7x + z) mod p",
        "  Append a single bit to denote positive or",
        "  negative y, halving the transmitted data.",
      ],
    },
    {
      id: 4,
      name: "Example_of_existential_attack_without_padding",
      title: "Existential Attack Without Padding",
      category: "Digital Signatures",
      file: "Example_of_existential_attack_without_padding.pdf",
      description: "Demonstrates an existential forgery attack when no padding scheme is used.",
      content: [
        "Existential forgery attack without padding.",
        "Setup: p=5, q=11, n=55 (public),",
        "e=3 (public), d=27 (private).",
        "",
        "The attacker forges a signature without",
        "knowing d. They simply pick a random s,",
        "e.g. s=2.",
        "",
        "Compute: m = s^e mod n = 2^3 mod 55 = 8.",
        "Present (m=8, s=2) as a forged pair.",
        "",
        "Verification: s^e mod n = 2^3 mod 55 = 8,",
        "which matches m. The forgery passes",
        "verification without the private key.",
      ],
    },
    {
      id: 5,
      name: "Existential_forgeries_and_how_padding_schemes_can_protect",
      title: "Existential Forgeries & Padding Protection",
      category: "Digital Signatures",
      file: "Existential_forgeries_and_how_padding_schemes_can_protect.pdf",
      description: "How padding schemes defend against existential forgery attacks on digital signatures.",
      content: [
        "Existential forgery: an attacker produces a valid",
        "(m, s) pair without knowing the private key.",
        "With access to Alice's public key (n, e), they",
        "compute m' = s^e mod n, which always yields a",
        "valid pair. Forgery is trivial on unpadded RSA.",
        "",
        "A scheme like PSS or PKCS#1 enforces that a",
        "valid message must follow a strict, recognisable",
        "structure. A randomly forged m = s^e mod n is",
        "unlikely to match this structure.",
        "",
        "Adding a hash function makes it harder still:",
        "the forged m would need to be a valid hash",
        "output, which the attacker cannot control.",
        "Existential forgery becomes computationally",
        "infeasible because the attacker can no longer",
        "freely choose s and get a meaningful m.",
        "",
        "Signing scheme:",
        "  Signer:   m -> hash -> pad -> s",
        "            pad(hash(m))^d mod n",
        "  Verifier: s -> s^e -> check pad/hash vs m",
      ],
    },
    {
      id: 6,
      name: "HMAC_construction",
      title: "HMAC Construction",
      category: "Message Authentication",
      file: "HMAC_construction.pdf",
      description: "Details the construction and inner workings of HMAC (Hash-based Message Authentication Code).",
      content: [
        "HMAC = H((K XOR opad) || H((K XOR ipad) || m))",
        "",
        "HMAC uses a hash function (e.g. SHA-256) with a",
        "secret key K and a two-pass structure.",
        "K is XORed with two padding constants:",
        "  ipad (inner pad) and opad (outer pad).",
        "",
        "An inner hash is computed over the padded key",
        "concatenated with the message. An outer hash is",
        "then computed over the other padded key plus the",
        "inner hash result. The output is the MAC, which",
        "any party holding K can verify.",
        "",
        "Why not simply H(K || m)?",
        "A naive hash of key+message is vulnerable to a",
        "length-extension attack. Merkle-Damgard hash",
        "functions (SHA-2, MD5) let an attacker who knows",
        "H(K||m) compute H(K||m||extra) without knowing K.",
        "",
        "HMAC defeats this because the inner hash result",
        "is re-hashed with a separately padded key, so",
        "the attacker cannot extend it without knowing K.",
      ],
    },
    {
      id: 7,
      name: "Padding_oracle_attack",
      title: "Padding Oracle Attack",
      category: "Block Ciphers",
      file: "Padding_oracle_attack.pdf",
      description: "Explains the padding oracle attack on CBC-mode block ciphers.",
      content: [
        "A padding oracle attack is a side-channel attack",
        "on CBC-mode block ciphers.",
        "",
        "The attacker submits modified ciphertext to a",
        "server. The server decrypts and reveals, through",
        "error messages or timing differences, whether",
        "the padding is valid or not.",
        "",
        "This 'oracle' leaks one bit of information per",
        "query. By systematically flipping bits and",
        "observing valid/invalid padding responses, the",
        "attacker can reverse-engineer the plaintext",
        "without ever knowing the key.",
        "",
        "Root cause: encryption without authentication.",
        "The system decrypts first, then checks padding,",
        "leaking internal state to the attacker.",
      ],
    },
    {
      id: 8,
      name: "RSA_example",
      title: "RSA Example",
      category: "Public Key Cryptography",
      file: "RSA_example.pdf",
      description: "Step-by-step worked example of RSA key generation, encryption, and decryption.",
      content: [
        "Step-by-step RSA key generation example.",
        "",
        "1. Choose two primes: p=7, q=11.",
        "2. Compute n = p * q = 77.",
        "3. Euler's totient: phi(n) = (p-1)(q-1) = 60.",
        "4. Choose public exponent e",
        "   (must be coprime to phi(n)).",
        "5. Compute private exponent:",
        "   d = e^(-1) mod phi(n).",
        "",
        "Public key  = (e, n)",
        "Private key = (d, n)",
        "",
        "Encrypt: C = m^e mod n",
        "Decrypt: C^d = m^(ed) mod n (recovers m)",
      ],
    },
    {
      id: 9,
      name: "Unknown_generator_point_order_security_risks",
      title: "Unknown Generator Point Order Security Risks",
      category: "Elliptic Curves",
      file: "Unknown_generator_point_order_security_risks.pdf",
      description: "Security risks when the order of the generator point on an elliptic curve is unknown.",
      content: [
        "1. Small subgroup attacks: if order n is small or",
        "   has small prime factors, an attacker can confine",
        "   the ECDH secret to a tiny subgroup, recovering",
        "   private keys with minimal computation",
        "   (Pohlig-Hellman).",
        "",
        "2. Without knowing n, the implementation cannot",
        "   validate that a public key lies on the correct",
        "   curve/subgroup. A malicious point on a weak",
        "   twist or wrong subgroup leaks private key bits.",
        "",
        "3. Failure of cryptographic hardness: ECC security",
        "   relies on ECDLP being hard, which requires n",
        "   to be a large prime. An unknown order may be",
        "   composite or smooth, making DLP tractable via",
        "   Pohlig-Hellman.",
        "",
        "4. No cofactor mitigation: standard curves publish",
        "   cofactor h = #E/n. Without knowing n, cofactor",
        "   multiplication cannot be applied correctly.",
        "",
        "5. Non-compliance with security standards (NIST).",
      ],
    },
  ],
};

export default cryptography;
