const cryptography = {
  id: "cryptography",
  title: "Cryptography",
  description: "Cryptographic protocols, attacks, and constructions.",
  basePath: "/modules/cryptography",
  notes: [
    {
      id: 1,
      name: "Birthday_paradox",
      title: "Birthday Paradox",
      category: "Hash Functions",
      file: "Birthday_paradox.pdf",
      description: "Explores the birthday paradox and its implications for hash collision probability.",
    },
    {
      id: 2,
      name: "Diffie_Hellman_example",
      title: "Diffie-Hellman Key Exchange Example",
      category: "Key Exchange",
      file: "Diffie_Hellman_example.pdf",
      description: "Worked example of the Diffie-Hellman key exchange protocol.",
    },
    {
      id: 3,
      name: "ECDH_example",
      title: "Elliptic Curve Diffie-Hellman Example",
      category: "Key Exchange",
      file: "ECDH_example.pdf",
      description: "Worked example of ECDH key exchange using elliptic curve cryptography.",
    },
    {
      id: 4,
      name: "Example_of_existential_attack_without_padding",
      title: "Existential Attack Without Padding",
      category: "Digital Signatures",
      file: "Example_of_existential_attack_without_padding.pdf",
      description: "Demonstrates an existential forgery attack when no padding scheme is used.",
    },
    {
      id: 5,
      name: "Existential_forgeries_and_how_padding_schemes_can_protect",
      title: "Existential Forgeries & Padding Protection",
      category: "Digital Signatures",
      file: "Existential_forgeries_and_how_padding_schemes_can_protect.pdf",
      description: "How padding schemes defend against existential forgery attacks on digital signatures.",
    },
    {
      id: 6,
      name: "HMAC_construction",
      title: "HMAC Construction",
      category: "Message Authentication",
      file: "HMAC_construction.pdf",
      description: "Details the construction and inner workings of HMAC (Hash-based Message Authentication Code).",
    },
    {
      id: 7,
      name: "Padding_oracle_attack",
      title: "Padding Oracle Attack",
      category: "Block Ciphers",
      file: "Padding_oracle_attack.pdf",
      description: "Explains the padding oracle attack on CBC-mode block ciphers.",
    },
    {
      id: 8,
      name: "RSA_example",
      title: "RSA Example",
      category: "Public Key Cryptography",
      file: "RSA_example.pdf",
      description: "Step-by-step worked example of RSA key generation, encryption, and decryption.",
    },
    {
      id: 9,
      name: "Unknown_generator_point_order_security_risks",
      title: "Unknown Generator Point Order Security Risks",
      category: "Elliptic Curves",
      file: "Unknown_generator_point_order_security_risks.pdf",
      description: "Security risks when the order of the generator point on an elliptic curve is unknown.",
    },
  ],
};

export default cryptography;
