const data_visualisation = {
  id: "data_visualisation",
  title: "Data Visualisation",
  description: "Data visualisation principles, graph design, R programming, and evaluation methods.",
  basePath: "/modules/data_visualisation",
  directories: [
    {
      id: "lecture_1",
      name: "Lecture 1",
      description: "Introduction to data visualisation",
      notes: [
        {
          id: 1,
          name: "Why_visualise",
          title: "Why Visualise & Common Visualisations",
          category: "Introduction",
          file: "Why_visualise.pdf",
          description: "Overview of common information visualisations and motivations for creating them.",
          content: [
            "Common information visualisations include bar charts,",
            "line graphs, pie charts, scatter plots, maps, and",
            "network diagrams.",
            "",
            "Visualisation helps us understand data that is too",
            "complex for raw numbers alone.",
            "",
            "Humans are visual thinkers; visual encodings leverage",
            "our natural spatial reasoning abilities.",
            "",
            "Key purposes of visualisation:",
            "  - Exploration: discover unknown patterns",
            "  - Explanation: communicate findings clearly",
            "  - Confirmation: verify hypotheses about data",
            "  - Presentation: share results with stakeholders",
            "",
            "Well-designed charts reveal patterns, outliers, and",
            "trends at a glance that would be invisible in tables",
            "of raw numbers.",
          ],
        },
        {
          id: 2,
          name: "Anscombes_quartet",
          title: "Anscombe's Quartet",
          category: "Introduction",
          file: "Anscombes_quartet.pdf",
          description: "Anscombe's quartet demonstrating why visualisation matters beyond summary statistics.",
          content: [
            "Anscombe's Quartet: four datasets with identical",
            "summary statistics (mean, variance, correlation,",
            "and regression line).",
            "",
            "Despite identical statistics, the four datasets look",
            "very different when plotted:",
            "",
            "  Dataset I:   Linear relationship",
            "  Dataset II:  Curved / parabolic relationship",
            "  Dataset III: Linear with one influential outlier",
            "  Dataset IV:  Vertical cluster with one outlier",
            "",
            "This demonstrates that summary statistics alone can",
            "be deeply misleading about the nature of data.",
            "",
            "Visualisation is essential to truly understand data",
            "distribution, relationships, and patterns.",
          ],
        },
        {
          id: 3,
          name: "Reasons_for_visualisation",
          title: "Reasons for Visualisation & Support Reasoning",
          category: "Introduction",
          file: "Reasons_for_visualisation.pdf",
          description: "Summary of key reasons for visualisation and how it supports reasoning.",
          content: [
            "Key reasons for visualisation:",
            "  - Explore: find new patterns in unfamiliar data",
            "  - Explain: make complex data understandable",
            "  - Confirm: test expectations against reality",
            "  - Present: communicate findings effectively",
            "",
            "Visualisation supports reasoning by externalising",
            "cognition -- moving mental work into the visual",
            "domain.",
            "",
            "It reduces cognitive load by offloading memory to",
            "the visual display (no need to remember all values).",
            "",
            "Amplifies perception through pre-attentive",
            "processing: colour, size, and orientation are",
            "detected instantly without conscious effort.",
            "",
            "Enables pattern recognition at a glance and helps",
            "communicate complex findings to non-technical",
            "audiences.",
          ],
        },
      ],
    },
    {
      id: "lecture_2",
      name: "Lecture 2",
      description: "Data processing and transformation",
      notes: [
        {
          id: 1,
          name: "Visualisation_process",
          title: "The Visualisation Process",
          category: "Data & Processing",
          file: "Visualisation_process.pdf",
          description: "Overview of the end-to-end visualisation process from data to display.",
          content: [
            "The visualisation process pipeline:",
            "  Raw Data -> Transform -> Visual Mapping ->",
            "  Render -> Display",
            "",
            "1. Data Collection: gather relevant datasets",
            "2. Transformation: convert data into usable form",
            "3. Visual Mapping: assign data variables to visual",
            "   properties (position, colour, size, shape)",
            "4. Rendering: produce the actual graphical output",
            "5. Display: present to the viewer",
            "",
            "The process is iterative: you refine each stage",
            "based on feedback and new understanding.",
            "",
            "Each stage involves design decisions that affect",
            "the final visualisation's clarity and accuracy.",
          ],
        },
        {
          id: 2,
          name: "Stages_of_visualisation",
          title: "Stages of Visualisation",
          category: "Data & Processing",
          file: "Stages_of_visualisation.pdf",
          description: "The key stages involved in creating a visualisation.",
          content: [
            "Seven stages of visualisation:",
            "",
            "1. Acquire:    Obtain data (file, API, database)",
            "2. Parse:      Structure data, assign types",
            "3. Filter:     Remove noise, focus on relevant",
            "               subsets",
            "4. Mine:       Extract patterns, apply statistics",
            "5. Represent:  Map data to visual form",
            "6. Refine:     Improve clarity, labels, colours",
            "7. Interact:   Allow user exploration (zoom,",
            "               filter, hover, select)",
            "",
            "These stages are not strictly linear; you often",
            "iterate back to earlier stages as understanding",
            "develops.",
          ],
        },
        {
          id: 3,
          name: "Data_transformation",
          title: "Data Transformation",
          category: "Data & Processing",
          file: "Data_transformation.pdf",
          description: "Techniques for transforming raw data into suitable formats for visualisation.",
          content: [
            "Transformation converts raw data into a format",
            "suitable for visualisation.",
            "",
            "Common transformation operations:",
            "",
            "  Aggregation:   Combine values (sum, mean, count)",
            "  Normalisation: Scale to common range (e.g. 0-1)",
            "  Sorting:       Order data for better comparison",
            "  Binning:       Group continuous data into",
            "                 discrete intervals (histograms)",
            "  Derived values: Compute new columns from",
            "                 existing ones (e.g. percentages,",
            "                 ratios, differences)",
            "",
            "The goal is to structure data so that visual",
            "mappings can clearly communicate patterns.",
          ],
        },
        {
          id: 4,
          name: "Refine_and_interact",
          title: "Refine & Interact",
          category: "Data & Processing",
          file: "Refine_and_interact.pdf",
          description: "The refine and interact stages of the visualisation pipeline.",
          content: [
            "REFINE: Improve visual clarity",
            "  - Better labels, colour choices, layout",
            "  - Remove chart junk (unnecessary gridlines,",
            "    decorations, borders)",
            "  - Maximise data-ink ratio: show data, minimise",
            "    non-data ink (Tufte's principle)",
            "",
            "INTERACT: Enable user-driven exploration",
            "  - Selection: click to highlight elements",
            "  - Filtering: show/hide data subsets",
            "  - Zooming & Panning: focus on regions",
            "  - Brushing: highlight by dragging over area",
            "  - Linking: interaction in one view updates",
            "    another (linked/coordinated views)",
            "",
            "Refinement and interaction together transform a",
            "static chart into an effective analysis tool.",
          ],
        },
        {
          id: 5,
          name: "Interaction_for_exploration",
          title: "Interaction is Vital for Exploration",
          category: "Data & Processing",
          file: "Interaction_for_exploration.pdf",
          description: "Why interaction is essential for exploratory data analysis.",
          content: [
            "Interaction is vital for exploratory data analysis.",
            "",
            "Static visualisations only show one perspective;",
            "interactive tools let users ask follow-up questions",
            "of the data.",
            "",
            "Shneiderman's Visual Information Seeking Mantra:",
            '  "Overview first, zoom and filter, then',
            '   details on demand."',
            "",
            "Focus + Context: show detail in one area while",
            "maintaining the bigger picture (e.g. fisheye lens).",
            "",
            "Dynamic Queries: direct manipulation widgets to",
            "filter data in real time (sliders, checkboxes).",
            "",
            "Brushing & Linking: highlight a subset in one view",
            "and see the same subset highlighted in all other",
            "linked views simultaneously.",
          ],
        },
        {
          id: 6,
          name: "Data_processing",
          title: "How to Process Data",
          category: "Data & Processing",
          file: "Data_processing.pdf",
          description: "Practical approaches to processing data for visualisation.",
          content: [
            "How to process data for visualisation:",
            "",
            "1. Import:    Load from CSV, JSON, databases,",
            "              or APIs",
            "2. Inspect:   Check dimensions, column types,",
            "              missing values, basic stats",
            "3. Clean:     Handle missing data, remove",
            "              duplicates, fix errors",
            "4. Transform: Reshape (pivot, melt), join",
            "              tables, create new features",
            "5. Validate:  Ensure processed data is correct",
            "              and complete (spot checks, asserts)",
            "6. Document:  Record all processing steps for",
            "              reproducibility",
            "",
            "Good data processing is the foundation of",
            "trustworthy visualisation.",
          ],
        },
        {
          id: 7,
          name: "Data_taxonomy_and_types",
          title: "Data Taxonomy & Data Types",
          category: "Data & Processing",
          file: "Data_taxonomy_and_types.pdf",
          description: "Classification of data types: nominal, ordinal, interval, and ratio.",
          content: [
            "Data taxonomy classifies data into types that",
            "determine suitable visualisations:",
            "",
            "Nominal:  Categories with no inherent order",
            "          (e.g. colour, country, genre)",
            "Ordinal:  Categories with meaningful order",
            "          (e.g. rating: low / medium / high)",
            "Interval: Numeric with meaningful distances",
            "          but no true zero (e.g. Celsius, year)",
            "Ratio:    Numeric with a true zero allowing",
            "          meaningful ratios (e.g. weight, age)",
            "",
            "Choosing the right data type classification",
            "guides which visual encoding to use:",
            "  - Nominal -> colour hue, shape",
            "  - Ordinal -> colour saturation, size",
            "  - Interval/Ratio -> position, length",
          ],
        },
        {
          id: 8,
          name: "Dimensions_and_measures",
          title: "Dimensions & Measures",
          category: "Data & Processing",
          file: "Dimensions_and_measures.pdf",
          description: "Ratio data with fixed zero, and the distinction between dimensions and measures.",
          content: [
            "Ratio data has a fixed zero point, allowing",
            "meaningful ratios (e.g. 20kg is twice 10kg).",
            "",
            "Dimensions vs Measures:",
            "",
            "Dimensions: Categorical fields used to slice or",
            "  group data (e.g. region, product, year).",
            "  They define the structure of the visualisation.",
            "",
            "Measures: Numeric/quantitative fields that are",
            "  aggregated (e.g. sales, count, temperature).",
            "  They provide the values being visualised.",
            "",
            "In tools like Tableau:",
            "  - Dimensions go on axes, colours, or shapes",
            "  - Measures are summed, averaged, or counted",
            "",
            "Understanding this distinction drives effective",
            "chart design and appropriate aggregation.",
          ],
        },
        {
          id: 9,
          name: "Data_type_examples",
          title: "Data Type Examples",
          category: "Data & Processing",
          file: "Data_type_examples.pdf",
          description: "Practical examples of data types: year of birth as interval, age as ratio, etc.",
          content: [
            "Practical examples of data type classification:",
            "",
            "Year of birth:  Interval (differences meaningful,",
            "                no true zero -- year 0 arbitrary)",
            "Age:            Ratio (has true zero, ratios",
            "                meaningful: 40 is twice 20)",
            "Temp in Celsius: Interval (0C is not absence",
            "                of temperature)",
            "Temp in Kelvin: Ratio (0K is absolute zero)",
            "Movie rating:   Ordinal (1-5 stars, ordered",
            "                but gaps not necessarily equal)",
            "Genre:          Nominal (no inherent order)",
            "",
            "Correctly classifying data determines:",
            "  - Appropriate visualisation types",
            "  - Valid statistical operations",
            "  - Meaningful comparisons",
          ],
        },
        {
          id: 10,
          name: "Data_cleaning_and_filtering",
          title: "Data Cleaning & Filtering",
          category: "Data & Processing",
          file: "Data_cleaning_and_filtering.pdf",
          description: "Handling missing data, erroneous values, type conversion, and entity resolution.",
          content: [
            "Data cleaning handles missing, erroneous, and",
            "inconsistent data.",
            "",
            "Missing data strategies:",
            "  - Remove rows with missing values",
            "  - Impute: fill with mean, median, or mode",
            "  - Flag as unknown / separate category",
            "",
            "Erroneous values: detect via range checks, type",
            "validation, and cross-referencing sources.",
            "",
            "Type conversion: ensure columns have correct",
            "types (e.g. string -> date, char -> numeric).",
            "",
            "Entity resolution: merge records that refer to",
            "the same real-world entity (deduplication).",
            "",
            "Filtering: focus analysis on relevant subsets",
            "of data to reduce noise and improve clarity.",
            "",
            "Clean data is foundational to trustworthy",
            "visualisation.",
          ],
        },
        {
          id: 11,
          name: "Data_adjustment_and_visual_language",
          title: "Data Adjustment, Visual Language & R Structures",
          category: "Data & Processing",
          file: "Data_adjustment_and_visual_language.pdf",
          description: "Data adjustment techniques (roll up, drill down), visual language sign systems, and R data structures.",
          content: [
            "Data adjustment techniques:",
            "  Roll Up:    Aggregate to higher level",
            "              (daily sales -> monthly totals)",
            "  Drill Down: Disaggregate to finer detail",
            "              (national -> regional -> city)",
            "",
            "Visual Language -- a sign system:",
            "  Marks encode data: points, lines, areas",
            "",
            "Bertin's visual variables:",
            "  Position, Size, Shape, Value (lightness),",
            "  Colour (hue), Orientation, Texture",
            "",
            "Each variable has different properties:",
            "  - Selective: can isolate a category",
            "  - Associative: can group elements",
            "  - Quantitative: can show magnitude",
            "  - Order: can show ranking",
            "",
            "R data structures: vectors, lists, matrices,",
            "data frames (introduced here, detailed next).",
          ],
        },
      ],
    },
    {
      id: "lecture_3",
      name: "Lecture 3",
      description: "Design principles, graph types, and R programming",
      notes: [
        {
          id: 1,
          name: "R_data_structures",
          title: "R Data Structures",
          category: "R Programming",
          file: "R_data_structures.pdf",
          description: "Lists, matrices, and dataframes in R; homogeneous vs heterogeneous structures; inner_join.",
          content: [
            "R data structures:",
            "",
            "Vectors: Homogeneous (all same type)",
            '  Created with c(1, 2, 3) or c("a", "b")',
            "",
            "Lists: Heterogeneous, can hold different types",
            '  and nested structures. list(name="X", val=3)',
            "",
            "Matrices: 2D homogeneous",
            "  matrix(data, nrow, ncol)",
            "",
            "Data Frames: 2D heterogeneous (like a table)",
            "  Most commonly used for data analysis in R.",
            "  data.frame(col1=..., col2=...)",
            "",
            "inner_join(): Merges two data frames on a",
            "  shared key column (only matching rows kept).",
            "",
            'Access: df$column, df[["col"]], df[row, col]',
          ],
        },
        {
          id: 2,
          name: "Mackinlays_design_algorithm",
          title: "Mackinlay's Design Algorithm & APT",
          category: "Design Principles",
          file: "Mackinlays_design_algorithm.pdf",
          description: "Mackinlay's APT (A Presentation Tool): automated design search over expressiveness and effectiveness.",
          content: [
            "Mackinlay's APT (A Presentation Tool) automates",
            "visualisation design decisions.",
            "",
            "Two core criteria:",
            "",
            "1. Expressiveness:",
            "   The visualisation shows ALL and ONLY the data",
            "   relationships that exist in the dataset.",
            "   (Don't imply false patterns; don't hide real ones)",
            "",
            "2. Effectiveness:",
            "   Use the most perceptually effective encoding",
            "   for each data type (based on psychophysical",
            "   research into human perception).",
            "",
            "APT searches a space of possible visualisation",
            "designs and ranks them by these criteria.",
            "",
            "It formalised the idea that good visualisation",
            "design can be guided by systematic rules.",
          ],
        },
        {
          id: 3,
          name: "Effectiveness_ranking",
          title: "Effectiveness Ranking",
          category: "Design Principles",
          file: "Effectiveness_ranking.pdf",
          description: "Perceptual effectiveness ranking: position, length, angle, area, volume, colour density.",
          content: [
            "Perceptual effectiveness rankings:",
            "",
            "For QUANTITATIVE data (most to least accurate):",
            "  1. Position (most accurate)",
            "  2. Length",
            "  3. Angle / Slope",
            "  4. Area",
            "  5. Volume",
            "  6. Colour density / saturation",
            "",
            "For ORDINAL data:",
            "  Position > Density > Saturation > Hue >",
            "  Texture > Shape",
            "",
            "For NOMINAL data:",
            "  Position > Hue > Texture > Shape > Density",
            "",
            "Use the highest-ranked encoding for the most",
            "important variable in your visualisation.",
            "Lower-ranked channels suit secondary or",
            "categorical variables.",
          ],
        },
        {
          id: 4,
          name: "Design_principles",
          title: "Design Principles",
          category: "Design Principles",
          file: "Design_principles.pdf",
          description: "Principle of consistency, principle of importance ordering, and expressiveness criteria.",
          content: [
            "Core design principles for visualisation:",
            "",
            "Principle of Consistency:",
            "  Use the same visual encoding for the same type",
            "  of data throughout the visualisation. Don't mix",
            "  conventions (e.g. red=good in one chart,",
            "  red=bad in another).",
            "",
            "Principle of Importance Ordering:",
            "  Encode the most important data dimension with",
            "  the most perceptually effective visual channel",
            "  (position first, then length, etc.).",
            "",
            "Expressiveness Criterion:",
            "  A visualisation must express all the facts in",
            "  the data and ONLY the facts in the data.",
            "  Do not imply relationships that do not exist.",
            "",
            "Match data type to appropriate visual encoding.",
          ],
        },
        {
          id: 5,
          name: "APT_limitations",
          title: "APT Limitations & Variable Data Types",
          category: "Design Principles",
          file: "APT_limitations.pdf",
          description: "Limitations of APT (no networks, 3D, interaction) and uni/bi/tri/hyper variable data categories.",
          content: [
            "APT limitations:",
            "  - Cannot handle networks/graph structures",
            "  - No support for 3D visualisations",
            "  - No interactive or dynamic displays",
            "  - Only supports static 2D designs",
            "",
            "Variable data type categories by number of",
            "variables:",
            "",
            "Univariate:    One variable",
            "               (e.g. histogram, bar chart)",
            "Bivariate:     Two variables",
            "               (e.g. scatter plot)",
            "Trivariate:    Three variables",
            "               (e.g. bubble chart, 3D scatter)",
            "Hypervariate:  Many variables (multivariate)",
            "               (e.g. parallel coordinates,",
            "                heatmaps, Chernoff faces)",
            "",
            "The number of variables shapes which chart",
            "types are appropriate.",
          ],
        },
        {
          id: 6,
          name: "Univariate_and_bivariate_data",
          title: "Univariate & Bivariate Data",
          category: "Graph Types",
          file: "Univariate_and_bivariate_data.pdf",
          description: "Univariate analysis (single variable, independent on x) and bivariate data (scatter plots for relationships).",
          content: [
            "Univariate analysis: examines a single variable.",
            "  - Shown with histograms, bar charts, box plots",
            "  - The independent variable goes on x-axis",
            "  - Reveals distribution shape, central tendency,",
            "    spread, and outliers",
            "",
            "Bivariate data: examines the relationship",
            "between two variables.",
            "  - Scatter plots are the primary tool for",
            "    bivariate quantitative data",
            "  - X-axis: independent, Y-axis: dependent",
            "",
            "What to look for in scatter plots:",
            "  - Correlation: positive, negative, or none",
            "  - Clusters of related observations",
            "  - Outliers that deviate from the pattern",
            "  - Add trend/regression lines to quantify the",
            "    strength and direction of relationships",
          ],
        },
        {
          id: 7,
          name: "Trivariate_data_and_dot_charts",
          title: "Trivariate Data & Dot Charts",
          category: "Graph Types",
          file: "Trivariate_data_and_dot_charts.pdf",
          description: "3D scatter plots, 2D with mark properties, and dot charts for continuous quantitative data.",
          content: [
            "Trivariate data: three variables simultaneously.",
            "",
            "Approaches:",
            "  3D scatter plots: map x, y, z to three",
            "    quantitative variables (can be hard to read)",
            "  2D + mark properties: use a 2D plot with the",
            "    third variable mapped to size, colour, or",
            "    shape of marks",
            "  Bubble charts: x and y position + bubble size",
            "    encodes the third variable",
            "",
            "Dot charts:",
            "  - Display continuous quantitative data with",
            "    precision (individual points on a scale)",
            "  - Better than bar charts for showing values",
            "    without baseline distortion",
            "  - Dot alignment along a common axis makes",
            "    comparison easier and more accurate",
          ],
        },
        {
          id: 8,
          name: "Components_of_graphs",
          title: "Components of Graphs",
          category: "Graph Types",
          file: "Components_of_graphs.pdf",
          description: "Framework (measurement types, scales), content (specifiers: marks, lines, points), and labels.",
          content: [
            "A graph has three main components:",
            "",
            "1. FRAMEWORK: Defines the measurement space",
            "   - Axes and their scales",
            "   - Scale types: linear, logarithmic,",
            "     categorical",
            "   - Gridlines for reference",
            "",
            "2. CONTENT (Specifiers): The data marks",
            "   - Points: for individual values",
            "   - Lines: for trends or connections",
            "   - Bars/Areas: for comparisons and totals",
            "   - The marks that carry the actual data",
            "",
            "3. LABELS: Context and explanation",
            "   - Title: what the graph shows",
            "   - Axis labels: what each dimension represents",
            "   - Legends: decode colour/shape/size mappings",
            "   - Annotations: highlight specific findings",
          ],
        },
        {
          id: 9,
          name: "Visualisation_marks",
          title: "Visualisation Marks",
          category: "Graph Types",
          file: "Visualisation_marks.pdf",
          description: "Points (scatter), lines (trends/series), bars (individual values), and boxes (distributions).",
          content: [
            "Types of visualisation marks:",
            "",
            "Points (scatter):",
            "  Show individual data values in 2D space.",
            "  Each point = one observation.",
            "",
            "Lines:",
            "  Show trends, time series, or connections.",
            "  Imply continuity between data points.",
            "",
            "Bars:",
            "  Compare values between categories or groups.",
            "  Length encodes magnitude from a baseline.",
            "",
            "Boxes (box plots):",
            "  Show data distribution -- median, quartiles,",
            "  range, and outliers in a compact form.",
            "",
            "The choice of mark depends on data type and the",
            "question being asked. Combining marks (e.g.",
            "line + points) can enhance readability.",
          ],
        },
        {
          id: 10,
          name: "Scatter_and_line_graphs",
          title: "Scatter Plot & Line Graph",
          category: "Graph Types",
          file: "Scatter_and_line_graphs.pdf",
          description: "Scatter plots for bivariate quantitative data; line graphs for time series and continuous change.",
          content: [
            "Scatter plots:",
            "  - For bivariate quantitative data",
            "  - Each point = one observation (x, y values)",
            "  - Reveal correlation, clusters, outliers",
            "  - Add regression line to show trend direction",
            "",
            "Line graphs:",
            "  - For time series and continuous change",
            "  - X-axis is typically time",
            "  - Y-axis is the measured variable",
            "  - Lines connect sequential data points to",
            "    show trends and rate of change",
            "",
            "Best practices:",
            "  - Multiple series can be overlaid for",
            "    comparison (use distinct colours/styles)",
            "  - Use consistent axis scales when comparing",
            "    across charts",
            "  - Label axes clearly with units",
          ],
        },
        {
          id: 11,
          name: "Box_plots_and_heat_maps",
          title: "Box Plots, Heat Maps & Cross Tabs",
          category: "Graph Types",
          file: "Box_plots_and_heat_maps.pdf",
          description: "Box plots for comparing distributions, heat maps for cyclical data, and cross tabulation plots.",
          content: [
            "Box plots: display distribution via five-number",
            "summary:",
            "  - Minimum (or lower whisker)",
            "  - Q1 (25th percentile)",
            "  - Median (Q2, 50th percentile)",
            "  - Q3 (75th percentile)",
            "  - Maximum (or upper whisker)",
            "  - Outliers shown as individual points beyond",
            "    the whiskers (typically 1.5x IQR)",
            "  - Useful for comparing distributions across",
            "    groups side by side",
            "",
            "Heat maps:",
            "  - Colour-coded matrices showing magnitude",
            "    across two categorical axes",
            "  - Excellent for cyclical data (e.g. day of",
            "    week vs hour of day)",
            "",
            "Cross tabulation (contingency table) plots:",
            "  Show frequency of category combinations.",
          ],
        },
        {
          id: 12,
          name: "Histogram_and_pareto_chart",
          title: "Histogram & Pareto Chart",
          category: "Graph Types",
          file: "Histogram_and_pareto_chart.pdf",
          description: "Histograms for frequency distributions; Pareto charts combining bar and cumulative line graphs.",
          content: [
            "Histograms show frequency distributions of",
            "continuous data.",
            "  - Data divided into bins (intervals)",
            "  - Bar height shows count per bin",
            "  - Bars are adjacent (no gaps) unlike bar charts",
            "  - Bin width affects perception: too narrow =",
            "    noisy, too wide = hides detail",
            "",
            "Pareto chart: combines bar chart (descending",
            "order) with a cumulative line graph.",
            "  - Based on the 80/20 principle (Pareto principle)",
            "  - Bars show individual category contributions",
            "  - The line shows the running total (cumulative %)",
            "  - Useful for identifying the most significant",
            "    factors in a dataset",
          ],
        },
        {
          id: 13,
          name: "Bar_graphs_and_stacked_bars",
          title: "Bar Graphs & Stacked Bar Chart",
          category: "Graph Types",
          file: "Bar_graphs_and_stacked_bars.pdf",
          description: "Bar graphs for comparing individual values between groups; stacked bars for showing totals and relationships.",
          content: [
            "Bar graphs compare individual values between",
            "categories or groups.",
            "  - Bars can be vertical (column) or horizontal",
            "  - Horizontal bars better for long category labels",
            "  - Grouped bar charts: bars side-by-side for",
            "    sub-category comparison",
            "",
            "Stacked bar charts:",
            "  - Segments stacked within each bar",
            "  - Show both individual contributions and total",
            "  - Difficult to compare middle segments across bars",
            "  - 100% stacked bars show proportional composition",
            "    (each bar sums to 100%)",
          ],
        },
        {
          id: 14,
          name: "Bump_area_and_radar_graphs",
          title: "Bump Chart, Area Graph & Radar Graph",
          category: "Graph Types",
          file: "Bump_area_and_radar_graphs.pdf",
          description: "Bump charts for rank changes, area graphs for quantity comparison, radar graphs for cyclical data.",
          content: [
            "Bump charts: show rank changes over time.",
            "  - Each line represents an item",
            "  - Crossings show rank switches",
            "  - Useful for tracking relative positions",
            "    (e.g. league tables)",
            "",
            "Area graphs: like line graphs but filled beneath.",
            "  - Show quantity/magnitude comparison over time",
            "  - Stacked area graphs show cumulative totals",
            "",
            "Radar (spider/star) graphs:",
            "  - Multiple axes radiating from centre",
            "  - Good for comparing profiles across several",
            "    variables (e.g. skill assessments)",
            "  - Works well for cyclical data",
          ],
        },
        {
          id: 15,
          name: "Trellis_display",
          title: "Trellis Display & Pipe Operator",
          category: "Graph Types",
          file: "Trellis_display.pdf",
          description: "Trellis/small multiples displays and the R dplyr pipe operator (%>%) for data manipulation.",
          content: [
            "Trellis display (small multiples): grid of similar",
            "charts, each showing a data subset.",
            "  - Same scale and axes across all panels",
            "  - Each panel corresponds to a category level",
            "    (e.g. one panel per country)",
            "  - Introduced by Cleveland and Becker",
            "  - Powerful for spotting patterns across subgroups",
            "",
            "The R dplyr pipe operator (%>%):",
            "  - Chains data manipulation steps together",
            "  - data %>% filter() %>% arrange() passes",
            "    output of each step as input to the next",
            "  - Makes code readable left-to-right",
          ],
        },
        {
          id: 16,
          name: "Dplyr_functions",
          title: "dplyr Functions Overview",
          category: "R Programming",
          file: "Dplyr_functions.pdf",
          description: "Core dplyr verbs: filter(), arrange(), select(), mutate(), summarise() with filter details.",
          content: [
            "Core dplyr verbs for data manipulation in R:",
            "",
            "  filter():    Select rows based on conditions",
            "  arrange():   Sort rows by column values",
            "  select():    Choose which columns to keep",
            "  mutate():    Create new columns from existing",
            "  summarise(): Collapse rows into summary stats",
            "",
            "filter() uses logical operators:",
            "  ==, !=, >, <, >=, <=, &, |",
            "",
            "Multiple conditions can be combined with commas",
            "(implicit AND).",
          ],
        },
        {
          id: 17,
          name: "Dplyr_pipe_operations",
          title: "dplyr Pipe Operations Example",
          category: "R Programming",
          file: "Dplyr_pipe_operations.pdf",
          description: "Worked R code example: movies_df with chained filter, arrange, and select operations.",
          content: [
            "Worked example using R dplyr pipe operations:",
            "",
            "  movies_df %>%",
            "    filter(year > 2000) %>%",
            "    arrange(desc(rating)) %>%",
            "    select(title, rating)",
            "",
            "The pipe (%>%) passes the left side result to",
            "the right side function.",
            "",
            "Each step transforms the data incrementally:",
            "  filter: keeps rows where year > 2000",
            "  arrange: sorts by rating descending",
            "  select: keeps only title and rating columns",
            "",
            "Result: a clean, ordered subset of the original.",
          ],
        },
        {
          id: 18,
          name: "Mutate_and_group_by",
          title: "Mutate & Group By",
          category: "R Programming",
          file: "Mutate_and_group_by.pdf",
          description: "Creating new columns with mutate(), grouping data with group_by(), and counting with summarise(n()).",
          content: [
            "mutate() creates new columns derived from",
            "existing data.",
            "  Example: mutate(profit = revenue - cost)",
            "",
            "group_by() groups rows by one or more",
            "categorical variables.",
            "  After grouping, summarise() calculates",
            "  per-group statistics.",
            "",
            "  Example: group_by(genre) %>%",
            "           summarise(count = n())",
            "",
            "  n() counts the number of rows in each group.",
            "",
            "Combine group_by + summarise for aggregated",
            "summaries. Use ungroup() to remove grouping",
            "for subsequent operations.",
          ],
        },
        {
          id: 19,
          name: "Arrange_function",
          title: "Arrange Function",
          category: "R Programming",
          file: "Arrange_function.pdf",
          description: "Sorting with arrange(): multiple inputs left to right, desc() for descending order.",
          content: [
            "arrange() sorts data frame rows by one or more",
            "columns.",
            "",
            "  - Multiple sort keys applied left to right",
            "    (primary, secondary, etc.)",
            "  - Default order: ascending (smallest to",
            "    largest, A to Z)",
            "  - Use desc() to sort in descending order",
            "",
            "Example:",
            "  arrange(year, desc(rating))",
            "  Sorts by year ascending, then rating",
            "  descending within each year.",
            "",
            "Works naturally with the pipe operator for",
            "chained workflows.",
          ],
        },
        {
          id: 20,
          name: "Select_function",
          title: "Select Function",
          category: "R Programming",
          file: "Select_function.pdf",
          description: "Column selection with select(): ranges, exclusion, contains(), ends_with(), starts_with() helpers.",
          content: [
            "select() picks columns from a data frame.",
            "",
            "  By name:    select(title, year, rating)",
            "  Ranges:     select(title:rating) -- all columns",
            "              from title to rating",
            "  Exclude:    select(-id, -timestamp)",
            "",
            "Helper functions for flexible selection:",
            '  contains("str"):     columns containing string',
            '  ends_with("suffix"): columns ending with suffix',
            '  starts_with("pre"): columns starting with prefix',
            '  matches("regex"):    columns matching a regex',
          ],
        },
        {
          id: 21,
          name: "R_visualisation_dialects",
          title: "R Visualisation Dialects",
          category: "R Programming",
          file: "R_visualisation_dialects.pdf",
          description: "Three main R graphics systems: base (plot), lattice (multivariate), and ggplot2.",
          content: [
            "Three main R graphics systems:",
            "",
            "1. Base R (plot):",
            "   - Simple, quick; built-in, no packages needed",
            "   - Procedural: add elements one at a time",
            "",
            "2. Lattice:",
            "   - Designed for multivariate data, trellis",
            "   - Creates complete plots in one function call",
            "",
            "3. ggplot2:",
            "   - Elegant, layered grammar of graphics",
            "   - Builds plots in layers: data + aes + geoms",
            "   - Most popular for publication-quality graphics",
          ],
        },
        {
          id: 22,
          name: "Ggplot2_introduction",
          title: "ggplot2 Introduction",
          category: "R Programming",
          file: "Ggplot2_introduction.pdf",
          description: "ggplot2: elegant compact code, powerful for exploratory analysis, coherent consistent syntax.",
          content: [
            "ggplot2: elegant, compact code for powerful",
            "visualisations.",
            "  - Created by Hadley Wickham",
            "  - Based on the Grammar of Graphics",
            "  - Particularly useful for exploratory analysis",
            "",
            "Key strengths:",
            "  - Coherent, consistent syntax across chart types",
            "  - Layered approach: build complexity incrementally",
            "  - Easy to switch chart types by changing the geom",
            "  - Extensive theme system for customisation",
            "  - Large ecosystem of extension packages",
          ],
        },
        {
          id: 23,
          name: "Ggplot2_components",
          title: "ggplot2 Components & Aesthetics",
          category: "R Programming",
          file: "Ggplot2_components.pdf",
          description: "ggplot2 layered grammar: data, aesthetics mapping, geometric objects, scales, faceting, coordinates.",
          content: [
            "ggplot2 layered grammar components:",
            "",
            "  Data:        The data frame to visualise",
            "  Aesthetics:  Map variables to visual properties",
            "               (x, y, colour, size, shape)",
            "  Geoms:       Geometric objects (points, bars,",
            "               lines)",
            "  Scales:      Control data-to-aesthetics mapping",
            "               (axis limits, colour palettes)",
            "  Faceting:    Split into subset panels (trellis)",
            "  Coordinates: Coordinate system (cartesian,",
            "               polar, map)",
            "  Theme:       Visual styling (fonts, backgrounds)",
            "",
            "Syntax: ggplot(data, aes(x, y)) + geom_point()",
          ],
        },
        {
          id: 24,
          name: "Geometry_and_coordinates",
          title: "Geometry & Coordinates",
          category: "R Programming",
          file: "Geometry_and_coordinates.pdf",
          description: "Geom types (point, bar, line), coordinate systems (cartesian, polar, map, trans), basic histogram and bar plots.",
          content: [
            "Geom types define the visual representation:",
            "  geom_point():     scatter plots",
            "  geom_bar()/col(): bar charts",
            "  geom_line():      line graphs",
            "  geom_histogram(): histograms",
            "",
            "Coordinate systems:",
            "  coord_cartesian(): standard x-y (default)",
            "  coord_polar():     circular/radial (pie, radar)",
            "  coord_map():       map projections",
            "  coord_trans():     transformed axes (e.g. log)",
            "",
            "Basic examples:",
            "  Histogram: geom_histogram(binwidth=5)",
            '  Bar plot:  geom_bar(stat="identity")',
          ],
        },
        {
          id: 25,
          name: "Ggplot2_geom_types",
          title: "ggplot2 Geom Types",
          category: "R Programming",
          file: "Ggplot2_geom_types.pdf",
          description: "Extended geom catalogue: hci, density, area, boxplot, point, path, tile.",
          content: [
            "Extended geom catalogue in ggplot2:",
            "",
            "  geom_density(): smooth density estimate curve",
            "  geom_area():    filled area under a curve",
            "  geom_boxplot(): box-and-whisker plots",
            "  geom_point():   scatter/dot plots",
            "  geom_path():    connect points in data order",
            "  geom_tile():    rectangular heatmap tiles",
            "  geom_violin():  mirrored density plots",
            "",
            "Each geom has its own set of applicable",
            "aesthetics.",
            "",
            "Combine multiple geoms in layers for rich",
            "visualisations (e.g. points + smoothing line).",
          ],
        },
      ],
    },
    {
      id: "lecture_4",
      name: "Lecture 4",
      description: "Multivariate visualisation, tools, and evaluation",
      notes: [
        {
          id: 1,
          name: "Multivariate_visualisations_overview",
          title: "Common Multivariate Visualisations",
          category: "Multivariate Visualisation",
          file: "Multivariate_visualisations_overview.pdf",
          description: "Overview of Chernoff faces, Table Lens, parallel coordinates, and mosaic plots.",
          content: [
            "Common multivariate visualisation techniques:",
            "",
            "  Chernoff faces: map variables to facial",
            "    features (face size, eye shape, mouth curve)",
            "  Table Lens: interactive table with bars in",
            "    cells for quick comparison",
            "  Parallel coordinates: each variable is a",
            "    vertical axis; data items are polylines",
            "  Mosaic plots: nested rectangles representing",
            "    proportions across categorical variables",
            "",
            "These techniques handle more than 3 variables",
            "simultaneously.",
            "",
            "Trade-off between information density and",
            "readability.",
          ],
        },
        {
          id: 2,
          name: "Ggplot2_extensions_and_tools",
          title: "ggplot2 Extensions & Visualisation Tools",
          category: "Visualisation Tools",
          file: "Ggplot2_extensions_and_tools.pdf",
          description: "Tool taxonomy: chart typologies (Excel), analysis grammars (Vega, VizQL), component architectures (D3.js, Prefuse).",
          content: [
            "Tool taxonomy for data visualisation:",
            "",
            "Chart typologies (e.g. Excel, Google Charts):",
            "  - Pick from a catalogue of chart types",
            "  - Easy to use but limited in customisation",
            "",
            "Analysis grammars (e.g. Vega, VizQL/Tableau):",
            "  - Define rules for mapping data to visuals",
            "  - More flexible, declarative specifications",
            "",
            "Component architectures (e.g. D3.js, Prefuse):",
            "  - Build from low-level graphical primitives",
            "  - Maximum flexibility, steeper learning curve",
            "",
            "ggplot2 sits between grammar and component",
            "approaches.",
          ],
        },
        {
          id: 3,
          name: "Chart_typologies_vs_architecture",
          title: "Chart Typologies vs Component Architecture",
          category: "Visualisation Tools",
          file: "Chart_typologies_vs_architecture.pdf",
          description: "Pick-from-stock vs build-your-own approaches; evaluating visualisations for usability and utility.",
          content: [
            'Chart typologies ("pick from stock"):',
            "  - User selects a pre-defined chart type",
            "  - Pros: fast, easy, no coding needed",
            "  - Cons: limited customisation, may not fit",
            "    unusual data",
            "",
            'Component architecture ("build your own"):',
            "  - Construct visuals from primitives",
            "  - Pros: full control, any design possible",
            "  - Cons: requires programming, slower to produce",
            "",
            "Evaluation considers both:",
            "  Usability: how easy is the tool to use?",
            "  Utility: does the visualisation effectively",
            "  communicate the data?",
          ],
        },
        {
          id: 4,
          name: "Chernoff_faces_and_table_lens",
          title: "Chernoff Faces & Table Lens",
          category: "Multivariate Visualisation",
          file: "Chernoff_faces_and_table_lens.pdf",
          description: "Chernoff face examples and Table Lens visual mapping of quantitative values to bars.",
          content: [
            "Chernoff faces: each data row becomes a cartoon",
            "face.",
            "  - Variables mapped to facial features: face",
            "    width, eye size, eyebrow slant, nose length,",
            "    mouth shape, etc.",
            "  - Humans are naturally attuned to face",
            "    recognition, making differences noticeable",
            "  - Limitations: arbitrary feature mapping, can",
            "    be misleading, limited to ~15 variables",
            "",
            "Table Lens: interactive focus+context table.",
            "  - Quantitative values shown as horizontal bars",
            "    within table cells",
            "  - Users expand rows/columns of interest while",
            "    seeing the full dataset in context",
            "  - Combines detail and overview in one display",
          ],
        },
        {
          id: 5,
          name: "Mosaic_plot",
          title: "Mosaic Plot",
          category: "Multivariate Visualisation",
          file: "Mosaic_plot.pdf",
          description: "Mosaic plots for displaying proportions across categorical variables with nested rectangles.",
          content: [
            "Mosaic plots display proportions across",
            "categorical variables.",
            "  - Plot area recursively divided into nested",
            "    rectangles",
            "  - Width represents proportion of one variable",
            "  - Height represents proportion of a second",
            "    variable within that group",
            "  - Colour can encode a third variable or",
            "    highlight deviations from independence",
            "",
            "Useful for exploring relationships in",
            "contingency tables.",
            "  - Area of each tile is proportional to the",
            "    frequency of that combination",
            "  - Easy to spot over/under-represented",
            "    category combinations",
          ],
        },
        {
          id: 6,
          name: "Parallel_coordinates",
          title: "Parallel Coordinates",
          category: "Multivariate Visualisation",
          file: "Parallel_coordinates.pdf",
          description: "Parallel coordinate plots: variables along horizontal axis, data points as polylines across vertical axes.",
          content: [
            "Parallel coordinates: variables arranged as",
            "parallel vertical axes.",
            "  - Each data item is a polyline connecting its",
            "    values across all axes",
            "",
            "Patterns:",
            "  - Correlated variables: similar line slopes",
            "    between adjacent axes",
            "  - Crossing lines indicate inverse relationships",
            "  - Clusters appear as bundles of similar polylines",
            "",
            "  - Axis ordering matters: can reveal or hide",
            "    patterns",
            "  - Interactive brushing: select a range on one",
            "    axis to highlight matching lines",
            "  - Scales well to many variables; less well to",
            "    many data items (overplotting)",
          ],
        },
        {
          id: 7,
          name: "Meta_evaluation_approach",
          title: "Meta-Evaluation Approach",
          category: "Evaluation",
          file: "Meta_evaluation_approach.pdf",
          description: "Desirable evaluation features: generalisability, precision, realism; methodologies vs features.",
          content: [
            "Desirable features when evaluating visualisation",
            "tools:",
            "",
            "  Generalisability: results apply beyond the",
            "    specific test case",
            "  Precision: results are quantitatively",
            "    measurable and reproducible",
            "  Realism: evaluation reflects real-world usage",
            "",
            "No single method scores high on all three;",
            "there is always a trade-off.",
            "",
            "  Lab experiments: high precision, low realism",
            "  Field studies: high realism, lower precision",
            "  Heuristic evaluation: quick but less",
            "    generalisable",
            "",
            "Choose methodology based on which features",
            "matter most for the evaluation goal.",
          ],
        },
        {
          id: 8,
          name: "Quality_methods",
          title: "Quality Methods",
          category: "Evaluation",
          file: "Quality_methods.pdf",
          description: "Nested methods (observation, think-aloud), inspector evaluation (heuristics), observational context, FN dialogue.",
          content: [
            "Evaluation methods for visualisation quality:",
            "",
            "Observation: watch users interact with the",
            "  visualisation in context.",
            "",
            "Think-aloud: users verbalise their thought",
            "  process during tasks.",
            "  - Provides rich qualitative data about",
            "    usability issues",
            "",
            "Inspector (heuristic) evaluation: experts",
            "  assess against known usability principles.",
            "  - Fast and cheap but depends on expert quality",
            "",
            "Observation in context: naturalistic study in",
            "  real work environments.",
            "",
            "FN dialogue (Focus-group Narrative): facilitated",
            "  group discussions. Captures diverse perspectives",
            "  and use cases.",
          ],
        },
        {
          id: 9,
          name: "Evaluation_approach_and_exploration",
          title: "Evaluation Approach & Exploration Styles",
          category: "Evaluation",
          file: "Evaluation_approach_and_exploration.pdf",
          description: "Participant factors, fluid exploration styles, performance metrics, and evaluation challenges.",
          content: [
            "Participant factors affect evaluation outcomes:",
            "  expertise, domain knowledge, motivation.",
            "",
            "Fluid exploration styles:",
            "  - Systematic: structured, methodical approach",
            "  - Opportunistic: follow interesting leads",
            "  - Users explore differently depending on goals",
            "    and experience",
            "",
            "Performance metrics for evaluation:",
            "  - Task completion time",
            "  - Accuracy",
            "  - Error rate",
            "  - Satisfaction",
            "",
            "Challenges: measuring insight is hard; task-based",
            "metrics may miss real-world value. Longitudinal",
            "studies capture learning effects but are expensive.",
          ],
        },
        {
          id: 10,
          name: "Controlled_experiments",
          title: "Controlled Experiments",
          category: "Evaluation",
          file: "Controlled_experiments.pdf",
          description: "Quantitative evaluation: hypothesis, independent/dependent variables, control vs experimental groups.",
          content: [
            "Controlled experiments: the gold standard for",
            "quantitative evaluation.",
            "",
            "  Hypothesis: a testable prediction (e.g.",
            '    "Chart A leads to faster task completion")',
            "  Independent variable: what is manipulated",
            "    (e.g. chart type)",
            "  Dependent variable: what is measured",
            "    (e.g. time, accuracy)",
            "",
            "  Control group: baseline condition",
            "  Experimental group: new condition",
            "",
            "Designs:",
            "  Between-subjects: each participant uses one",
            "  Within-subjects: each uses all (counterbalanced)",
            "",
            "Statistical significance testing (p-values,",
            "confidence intervals) determines if differences",
            "are real. High precision but lower ecological",
            "validity.",
          ],
        },
      ],
    },
  ],
};

export default data_visualisation;
