const data_visualisation = {
  id: "data_visualisation",
  title: "Data Visualisation",
  description: "Data visualisation principles, graph design, R programming, and evaluation methods.",
  basePath: "/modules/data_visualisation",
  directories: [
    {
      id: "lecture_1",
      name: "Lecture 1",
      description: "Introduction to data visualisation",
      notes: [
        {
          id: 1,
          name: "Why_visualise",
          title: "Why Visualise & Common Visualisations",
          category: "Introduction",
          file: "Why_visualise.pdf",
          description: "Overview of common information visualisations and motivations for creating them.",
          content: [
            "Common information visualisations include bar charts,",
            "line graphs, pie charts, scatter plots, maps, and",
            "network diagrams.",
            "",
            "Visualisation helps us understand data that is too",
            "complex for raw numbers alone.",
            "",
            "Humans are visual thinkers; visual encodings leverage",
            "our natural spatial reasoning abilities.",
            "",
            "Key purposes of visualisation:",
            "  - Exploration: discover unknown patterns",
            "  - Explanation: communicate findings clearly",
            "  - Confirmation: verify hypotheses about data",
            "  - Presentation: share results with stakeholders",
            "",
            "Well-designed charts reveal patterns, outliers, and",
            "trends at a glance that would be invisible in tables",
            "of raw numbers.",
          ],
        },
        {
          id: 2,
          name: "Anscombes_quartet",
          title: "Anscombe's Quartet",
          category: "Introduction",
          file: "Anscombes_quartet.pdf",
          description: "Anscombe's quartet demonstrating why visualisation matters beyond summary statistics.",
          content: [
            "Anscombe's Quartet: four datasets with identical",
            "summary statistics (mean, variance, correlation,",
            "and regression line).",
            "",
            "Despite identical statistics, the four datasets look",
            "very different when plotted:",
            "",
            "  Dataset I:   Linear relationship",
            "  Dataset II:  Curved / parabolic relationship",
            "  Dataset III: Linear with one influential outlier",
            "  Dataset IV:  Vertical cluster with one outlier",
            "",
            "This demonstrates that summary statistics alone can",
            "be deeply misleading about the nature of data.",
            "",
            "Visualisation is essential to truly understand data",
            "distribution, relationships, and patterns.",
          ],
        },
        {
          id: 3,
          name: "Reasons_for_visualisation",
          title: "Reasons for Visualisation & Support Reasoning",
          category: "Introduction",
          file: "Reasons_for_visualisation.pdf",
          description: "Summary of key reasons for visualisation and how it supports reasoning.",
          content: [
            "Key reasons for visualisation:",
            "  - Explore: find new patterns in unfamiliar data",
            "  - Explain: make complex data understandable",
            "  - Confirm: test expectations against reality",
            "  - Present: communicate findings effectively",
            "",
            "Visualisation supports reasoning by externalising",
            "cognition -- moving mental work into the visual",
            "domain.",
            "",
            "It reduces cognitive load by offloading memory to",
            "the visual display (no need to remember all values).",
            "",
            "Amplifies perception through pre-attentive",
            "processing: colour, size, and orientation are",
            "detected instantly without conscious effort.",
            "",
            "Enables pattern recognition at a glance and helps",
            "communicate complex findings to non-technical",
            "audiences.",
          ],
        },
      ],
    },
    {
      id: "lecture_2",
      name: "Lecture 2",
      description: "Data processing and transformation",
      notes: [
        {
          id: 1,
          name: "Visualisation_process_and_stages",
          title: "Visualisation Process & Stages",
          category: "Data & Processing",
          file: "Visualisation_process_and_stages.pdf",
          description: "The visualisation process pipeline, data/visual/view transformations, and the seven stages (acquire, parse, filter, mine, visual mapping).",
          content: [
            "The Visualisation Process pipeline:",
            "  Data -> Data Transformation -> Dataset ->",
            "  Visual Mapping -> Visual Form -> Views ->",
            "  User Tasks + Visual Perception",
            "",
            "Key transformations:",
            "  Data Transformation: create structural model,",
            "    mapping raw data into a data table",
            "  Visual Mapping: create visual/spatial models",
            "    into visual structures",
            "  View Transformations: create views of the",
            "    visual structures (position, scaling, clipping)",
            "",
            "Seven stages: Acquire (obtain data), Parse",
            "(provide structure and order into categories),",
            "Filter (remove all but data of interest), Mine",
            "(apply methods/statistics to discern patterns),",
            "then Dataset -> Visual Form via Visual Mapping",
            "(choose a visual model: graph, list, or tree).",
          ],
        },
        {
          id: 2,
          name: "How_to_process_data",
          title: "How to Process Data",
          category: "Data & Processing",
          file: "How_to_process_data.pdf",
          description: "Data models, processing algorithms, visual encoding, and the three components of data models.",
          content: [
            "How to process data?",
            "  - Data models",
            "  - Processing algorithms",
            "",
            "How to encode data using images (the visual",
            "channel)? -> Visual encoding (mapping)",
            "",
            "Data Models are formal descriptions with",
            "three components:",
            "  - Objects: the entities being described",
            "  - Attributes: properties of those objects",
            "  - Relations: connections between objects",
            "",
            "Data models provide the foundation for",
            "deciding how to map data to visual form.",
          ],
        },
        {
          id: 3,
          name: "Data_taxonomy_and_types",
          title: "Data Taxonomy & Data Types",
          category: "Data & Processing",
          file: "Data_taxonomy_and_types.pdf",
          description: "Classification of data types: nominal, ordinal, interval; data dimensionality (1D, 2D, 3D, nD, temporal, trees, networks).",
          content: [
            "The Taxonomy of Data Types:",
            "  1D, 2D, 3D, nD, Temporal, Trees, Networks",
            "",
            "Nominal, Ordinal, Quantitative:",
            "",
            "N: Nominal (unordered categories)",
            "   Operators: =, !=",
            "   e.g. math, art, genre",
            "",
            "O: Ordinal (ordered categories)",
            "   Operators: =, !=, <, >",
            "   e.g. A, A-, B+",
            "",
            "Q: Interval (zero is arbitrary)",
            "   Operators: =, !=, <, >, -",
            "   Can measure distance",
            "   e.g. GPS coordinates, Celsius",
          ],
        },
        {
          id: 4,
          name: "Dimensions_and_measures",
          title: "Dimensions & Measures",
          category: "Data & Processing",
          file: "Dimensions_and_measures.pdf",
          description: "Ratio data type (zero fixed), and the distinction between dimensions (independent) and measures (dependent).",
          content: [
            "Ratio (zero fixed):",
            "  Operators: =, !=, >, <, -, %",
            "  Can measure ratios or proportions",
            "  e.g. age, weight, distance",
            "",
            "Dimensions and Measures:",
            "",
            "Dimensions (independent variables):",
            "  - Discrete variables describing data (N, O)",
            "  - Categories, dates, binned quantities",
            "  - e.g. gender, sex, region",
            "",
            "Measures (dependent variables):",
            "  - Data values that can be aggregated",
            "  - Quantitative fields (sum, avg, count)",
            "",
            "Understanding this distinction drives",
            "effective chart design.",
          ],
        },
        {
          id: 5,
          name: "Data_type_examples",
          title: "Data Type Examples & Processing Intro",
          category: "Data & Processing",
          file: "Data_type_examples.pdf",
          description: "Practical data type examples (YoB, age, sex) and introduction to data cleaning, filtering, and adjustment.",
          content: [
            "Practical data type examples:",
            "  Dim  YoB:    Q (interval)",
            "  Dim  Age:    Q (ratio)",
            "  Dim  Sex:    N (nominal)",
            "  Meas People: Q (ratio)",
            "  Marital status: Nominal (unordered)",
            "",
            "Data Processing:",
            "  Data cleaning and filtering",
            "  - For quality control",
            "  - Remove (outliers, missing data)",
            "  - Modify (conversion of format)",
            "",
            "Data adjustment:",
            "  - Depends on task and question to ask",
            "  - Uses relational algebra concepts",
            "  - Reformatting and reintegration",
          ],
        },
        {
          id: 6,
          name: "Data_cleaning_and_adjustment",
          title: "Data Cleaning, Adjustment & Visual Language",
          category: "Data & Processing",
          file: "Data_cleaning_and_adjustment.pdf",
          description: "Data cleaning (missing data, type conversion, entity resolution), relational algebra operations, data adjustment (roll up, drill down), and visual language as a sign system.",
          content: [
            "Data Cleaning and Filtering:",
            "  Missing data, erroneous values, type",
            "  conversion, entity resolution, data integration",
            "  Start with univariate summaries, then consider",
            "  relationships among variables.",
            "",
            "Data Adjustment & Relational Algebra:",
            "  Relational data model, SQL operations:",
            "  Projection (SELECT), Selection (WHERE),",
            "  Sorting (ORDER BY), Aggregation (GROUP BY),",
            "  Combine relations (UNION, JOIN)",
            "",
            "Data Adjustment: Roll Up -> smaller (aggregate),",
            "  Drill Down -> bigger (disaggregate)",
            "",
            "Visual Language is a sign system:",
            "  Sender encodes information in signs,",
            "  Receiver decodes. Hue encodes nominal,",
            "  Value (lightness) encodes ordinal/continuous.",
          ],
        },
        {
          id: 7,
          name: "Refine_and_interact",
          title: "Refine, Interact & Exploration",
          category: "Data & Processing",
          file: "Refine_and_interact.pdf",
          description: "The refine and interact stages of the pipeline, and why interaction is vital for exploration.",
          content: [
            "Dataset -> Visual Form -> Visual Mapping",
            "",
            "REFINE: Improve the basic representation",
            "  to make it clearer and more visually engaging.",
            "",
            "INTERACT: Visual Form -> Views via",
            "  View Transformations.",
            "  Add methods for manipulating the data or",
            "  controlling what features are visible.",
            "",
            "Interaction is vital for exploration:",
            "  Possible actions:",
            "  Select, Explore, Reconfigure,",
            "  Abstract/Elaborate, Filter,",
            "  Connect, Encode",
            "",
            "Interactive visualisation allows users to",
            "ask follow-up questions of the data.",
          ],
        },
        {
          id: 8,
          name: "R_data_structures_intro",
          title: "R Data Structures Introduction",
          category: "R Programming",
          file: "R_data_structures_intro.pdf",
          description: "Introduction to R vectors: numeric, character, and logical types.",
          content: [
            "R Data Structures (introduction):",
            "",
            "Vectors -- three main types:",
            "",
            "  Numeric:   x <- c(0, 2:4)",
            '  Character: y <- c("alpha", "b", "c3")',
            "  Logical:   z <- c(1, 0, TRUE, FALSE)",
            "",
            "Vectors are the fundamental data structure",
            "in R; all other structures build on them.",
            "",
            "Key properties:",
            "  - Homogeneous: all elements same type",
            "  - Indexed starting from 1 (not 0)",
            "  - Created with the c() function",
          ],
        },
      ],
    },
    {
      id: "lecture_3",
      name: "Lecture 3",
      description: "Design principles, graph types, and R programming",
      notes: [
        {
          id: 1,
          name: "R_data_structures",
          title: "R Data Structures",
          category: "R Programming",
          file: "R_data_structures.pdf",
          description: "Lists, matrices, and dataframes in R; homogeneous vs heterogeneous structures; inner_join.",
          content: [
            "R data structures:",
            "",
            "Vectors: Homogeneous (all same type)",
            '  Created with c(1, 2, 3) or c("a", "b")',
            "",
            "Lists: Heterogeneous, can hold different types",
            '  and nested structures. list(name="X", val=3)',
            "",
            "Matrices: 2D homogeneous",
            "  matrix(data, nrow, ncol)",
            "",
            "Data Frames: 2D heterogeneous (like a table)",
            "  Most commonly used for data analysis in R.",
            "  data.frame(col1=..., col2=...)",
            "",
            "inner_join(): Merges two data frames on a",
            "  shared key column (only matching rows kept).",
            "",
            'Access: df$column, df[["col"]], df[row, col]',
          ],
        },
        {
          id: 2,
          name: "Mackinlays_design_and_effectiveness",
          title: "Mackinlay's Design Algorithm & Effectiveness",
          category: "Design Principles",
          file: "Mackinlays_design_and_effectiveness.pdf",
          description: "Mackinlay's APT (A Presentation Tool), expressiveness and effectiveness criteria, and perceptual effectiveness ranking.",
          content: [
            "Mackinlay's APT (A Presentation Tool) automates",
            "visualisation design. Position is best for all.",
            "",
            "APT searches over a design space:",
            "  - Tests expressiveness of each visual encoding",
            "  - Ranked by perceptual effectiveness criteria",
            "  - Output: 'most effective' visualisation",
            "  - Only good for static visualisations",
            "",
            "Effectiveness ranking (most to least accurate):",
            "  1. Position",
            "  2. Length",
            "  3. Angle / Slopes",
            "  4. Area",
            "  5. Volume",
            "  6. Colour density",
            "",
            "A visualisation is more effective if the info",
            "conveyed is more readily perceived.",
          ],
        },
        {
          id: 3,
          name: "Design_principles_and_APT",
          title: "Design Principles & APT Limitations",
          category: "Design Principles",
          file: "Design_principles_and_APT.pdf",
          description: "Principle of consistency, importance ordering, expressiveness criteria, APT limitations, and variable data categories.",
          content: [
            "Principle of Consistency:",
            "  Properties of the image should match the",
            "  properties of the data.",
            "",
            "Principle of Importance Ordering:",
            "  Encode the most important information in",
            "  the most effective way.",
            "",
            "Expressiveness: (1) express all facts in the",
            "data, (2) only the facts in the data.",
            "",
            "Limitations of APT:",
            "  - Networks, hierarchies, maps not supported",
            "  - No 3D, animation, or interaction",
            "  - Does not consider semantics/conventions",
            "  - Assumes single visualisation as output",
            "",
            "Variable data categories:",
            "  Uni, Bi, Tri, Hyper (multivariate)",
            "Representations: points, lines, bars, boxes",
          ],
        },
        {
          id: 4,
          name: "Data_variable_types",
          title: "Univariate, Bivariate & Trivariate Data",
          category: "Graph Types",
          file: "Data_variable_types.pdf",
          description: "Univariate analysis (single variable), bivariate data (scatter plots), trivariate data (3D scatter, 2D + marks), and dot charts.",
          content: [
            "Univariate data: analyses a single variable.",
            "  Independent variable on x, dependent on y.",
            "  e.g. bar chart of heights by student number",
            "",
            "Bivariate data: analyses 2 variables.",
            "  Want to see the relationship between them.",
            "  Is there a linear curve or random pattern?",
            "  Scatter plot is commonly used.",
            "",
            "Trivariate data: 3 variables simultaneously.",
            "  3D scatter plot, or 2D + mark properties",
            "  (size, colour). Set of specific visualisations.",
            "",
            "Dot charts: for analysing values spaced at",
            "  irregular intervals. Continuous, quantitative,",
            "  univariate data.",
          ],
        },
        {
          id: 5,
          name: "Graph_components_and_marks",
          title: "Graph Components & Visualisation Marks",
          category: "Graph Types",
          file: "Graph_components_and_marks.pdf",
          description: "Framework, content (specifiers), and labels; plus visualisation marks: points, lines, bars, and boxes.",
          content: [
            "Components of graphs:",
            "  Framework: measurement types, scales",
            "  Content (Specifiers): marks, lines, points",
            "  Labels: title, axis ticks",
            "",
            "Visualisation marks:",
            "",
            "Points: scatter plots for 2 values. Can replace",
            "  bars when scale doesn't start at 0.",
            "",
            "Lines: connect values in a series. Show changes,",
            "  trends, patterns. Not for nominal/ordinal.",
            "",
            "Bars: emphasise individual values. Good for",
            "  comparing individual values between groups.",
            "",
            "Boxes: show distribution via quartiles.",
          ],
        },
        {
          id: 6,
          name: "Scatter_line_box_heat",
          title: "Scatter, Line, Box & Heat Map",
          category: "Graph Types",
          file: "Scatter_line_box_heat.pdf",
          description: "Scatter plots for bivariate data, line graphs for time series, box plots for distribution comparison, heat maps for cyclical data, and cross-tab plots.",
          content: [
            "Scatter plots: compare two quantitative",
            "  variables. Continuous bivariate data.",
            "  Shows relationships between variables.",
            "",
            "Line graphs: when quantitative values change",
            "  during a continuous period of time.",
            "  Time series data (non-cyclical).",
            "",
            "Box plots: comparison of data from different",
            "  categories. Graphically depicts groups of",
            "  numerical data through their quartiles.",
            "",
            "Heat maps: shows large quantities of cyclical",
            "  data. Can use colour or greyscale.",
            "",
            "Cross-tab plot: similar to heat map but uses",
            "  area instead of colour intensity.",
          ],
        },
        {
          id: 7,
          name: "Distribution_and_bar_charts",
          title: "Histogram, Pareto, Bar & Stacked Bar",
          category: "Graph Types",
          file: "Distribution_and_bar_charts.pdf",
          description: "Histograms for frequency distributions, Pareto charts (bar + cumulative line), bar graphs for comparison, and stacked bar charts.",
          content: [
            "Histogram: shows frequency distributions.",
            "  Continuous, quantitative, univariate data.",
            "",
            "Pareto chart: analyses frequency of problems",
            "  or causes. Contains both bar and line graph.",
            "  Line is cumulative percentage.",
            "",
            "Bar graphs: support comparison of individual",
            "  values between different groups.",
            "  Can run vertically or horizontally.",
            "",
            "Stacked bar chart: presents the total while",
            "  comparing relationships between groups.",
            "  Harder to compare the size of each category",
            "  within the stack.",
          ],
        },
        {
          id: 8,
          name: "Special_charts_and_trellis",
          title: "Bump, Area, Radar & Trellis Display",
          category: "Graph Types",
          file: "Special_charts_and_trellis.pdf",
          description: "Bump charts for rank, area graphs for quantity comparison, radar graphs for cyclical data, trellis displays, and the dplyr pipe operator.",
          content: [
            "Bump chart: similar to line graph but focuses",
            "  on rank rather than continuous values.",
            "",
            "Area graph: compare two or more quantities.",
            "  Area between axis and line emphasised with",
            "  colours and textures.",
            "",
            "Radar graph: represent data across a cyclical",
            "  nature of time. Multiple axes from centre.",
            "",
            "Trellis Display: varies one variable,",
            "  distributes different values across views.",
            "",
            "R dplyr pipe operator (%>%):",
            "  Chains operations: 1000 %>% sqrt %>% round",
            "  Take 1000, square root it, then round it.",
          ],
        },
        {
          id: 9,
          name: "Dplyr_core_functions",
          title: "dplyr Core Functions & Pipe Operations",
          category: "R Programming",
          file: "Dplyr_core_functions.pdf",
          description: "Core dplyr verbs (filter, arrange, select, mutate, summarise), pipe operations example with movies_df, mutate and group_by.",
          content: [
            "Core dplyr verbs:",
            "  filter():    subset rows by condition",
            "  arrange():   reorder rows in df",
            "  select():    select columns of interest",
            "  mutate():    create new columns from existing",
            "  summarise(): aggregate to single value",
            "",
            "Pipe example: movies_df %>%",
            "  filter(year > 2000, genre == 'comedy') %>%",
            "  arrange(desc(rating)) %>%",
            "  select(title, rating)",
            "",
            "mutate(data, new_col = function(old_cols))",
            "  e.g. cost_per_min = budget / length",
            "",
            "group_by() + summarise(n()) counts rows",
            "  per group.",
          ],
        },
        {
          id: 10,
          name: "Dplyr_arrange_and_select",
          title: "Arrange & Select Functions",
          category: "R Programming",
          file: "Dplyr_arrange_and_select.pdf",
          description: "Sorting with arrange() (multiple inputs, desc()), and column selection with select() (ranges, exclusion, helper functions).",
          content: [
            "arrange(data, column_to_sort_by):",
            "  Multiple inputs arranged left to right.",
            "  Use desc(column) for descending order.",
            "  e.g. desc(rating), desc(year) -- order matters",
            "",
            "select(movies_df, column_x, ...):",
            "  Exclude: select(movies_df, -c(r1:r10))",
            "  Range:   select(movie_df, title:votes)",
            "           (all cols from title to votes)",
            "",
            "Helper functions:",
            '  contains("r"): columns with "r" in name',
            '  ends_with("r"): columns ending with "r"',
            '  starts_with("r"): columns starting with "r"',
            '  starts_with("r[0-9]"): r1, r2, ..., r9',
          ],
        },
        {
          id: 11,
          name: "R_visualisation_and_ggplot2",
          title: "R Visualisation Dialects & ggplot2 Intro",
          category: "R Programming",
          file: "R_visualisation_and_ggplot2.pdf",
          description: "Three R graphics systems (base, lattice, ggplot2) and ggplot2's strengths: elegant code, consistent syntax, exploratory power.",
          content: [
            "R Fundamental Visualisation -- 3 main dialects:",
            "",
            "Base: with(airquality, plot(Temp, Ozone))",
            "Lattice: can handle multivariate",
            "  xyplot(Ozone ~ Temp, airquality)",
            "ggplot2: ggplot(airquality, aes(Temp, Ozone))",
            "  + geom_point()",
            "",
            "ggplot2: more elegant and compact code.",
            "  More aesthetically pleasing defaults than",
            "  lattice. Very powerful for exploratory data",
            "  analysis. Coherent, consistent syntax.",
            "  Defines basic components of a plot.",
            "  Easy to get started, plenty of power.",
          ],
        },
        {
          id: 12,
          name: "Ggplot2_grammar_and_geometry",
          title: "ggplot2 Grammar, Geometry & Coordinates",
          category: "R Programming",
          file: "Ggplot2_grammar_and_geometry.pdf",
          description: "ggplot2 layered grammar (data, aesthetics, geoms, scales, faceting, coordinates), geom types, and coordinate systems.",
          content: [
            "ggplot2 layered grammar:",
            "  Data: must be a dataframe in ggplot()",
            "  Aesthetics: map variables to x, y, colour,",
            "    size, shape, transparency",
            "  Geometric objects: what you see on the plot",
            "  Scales: map values from data to aesthetics",
            "  Faceting: subset data into multiple plots",
            "  Coordinates: put data on plane of graphic",
            "",
            "Geometry (Geom): points, lines, polygons",
            "  geom_point(), geom_bar(), geom_line()",
            "",
            "Coordinates: coord_cartesian(), coord_polar(),",
            "  coord_map(), coord_trans()",
            "",
            "Basic plots: geom_histogram(), geom_bar()",
          ],
        },
        {
          id: 13,
          name: "Ggplot2_geom_types",
          title: "ggplot2 Geom Types & Multivariate Intro",
          category: "R Programming",
          file: "Ggplot2_geom_types.pdf",
          description: "Extended geom catalogue (density, area, boxplot, point, path, tile) and introduction to common multivariate visualisations.",
          content: [
            "Extended geom catalogue in ggplot2:",
            "  geom_hci, geom_density(), geom_area(),",
            "  geom_boxplot(), geom_point(),",
            "  geom_path(), geom_tile()",
            "",
            "Common Multivariate Data Visualisations:",
            "  - Chernoff faces",
            "  - Table Lens",
            "  - Parallel coordinates",
            "  - Mosaic Plot",
            "",
            "Chernoff face: maps data variables to facial",
            "  features (eyes, nose, mouth) to represent",
            "  multivariate data visually. Humans are",
            "  naturally attuned to reading faces.",
          ],
        },
      ],
    },
    {
      id: "lecture_4",
      name: "Lecture 4",
      description: "Multivariate visualisation, tools, and evaluation",
      notes: [
        {
          id: 1,
          name: "Multivariate_visualisations_overview",
          title: "Common Multivariate Visualisations",
          category: "Multivariate Visualisation",
          file: "Multivariate_visualisations_overview.pdf",
          description: "Overview of Chernoff faces, Table Lens, parallel coordinates, and mosaic plots.",
          content: [
            "Common multivariate visualisation techniques:",
            "",
            "  Chernoff faces: map variables to facial",
            "    features (face size, eye shape, mouth curve)",
            "  Table Lens: interactive table with bars in",
            "    cells for quick comparison",
            "  Parallel coordinates: each variable is a",
            "    vertical axis; data items are polylines",
            "  Mosaic plots: nested rectangles representing",
            "    proportions across categorical variables",
            "",
            "These techniques handle more than 3 variables",
            "simultaneously.",
            "",
            "Trade-off between information density and",
            "readability.",
          ],
        },
        {
          id: 2,
          name: "Ggplot2_extensions_and_tools",
          title: "ggplot2 Extensions & Visualisation Tools",
          category: "Visualisation Tools",
          file: "Ggplot2_extensions_and_tools.pdf",
          description: "Tool taxonomy: chart typologies (Excel), analysis grammars (Vega, VizQL), component architectures (D3.js, Prefuse).",
          content: [
            "Tool taxonomy for data visualisation:",
            "",
            "Chart typologies (e.g. Excel, Google Charts):",
            "  - Pick from a catalogue of chart types",
            "  - Easy to use but limited in customisation",
            "",
            "Analysis grammars (e.g. Vega, VizQL/Tableau):",
            "  - Define rules for mapping data to visuals",
            "  - More flexible, declarative specifications",
            "",
            "Component architectures (e.g. D3.js, Prefuse):",
            "  - Build from low-level graphical primitives",
            "  - Maximum flexibility, steeper learning curve",
            "",
            "ggplot2 sits between grammar and component",
            "approaches.",
          ],
        },
        {
          id: 3,
          name: "Chart_typologies_vs_architecture",
          title: "Chart Typologies vs Component Architecture",
          category: "Visualisation Tools",
          file: "Chart_typologies_vs_architecture.pdf",
          description: "Pick-from-stock vs build-your-own approaches; evaluating visualisations for usability and utility.",
          content: [
            'Chart typologies ("pick from stock"):',
            "  - User selects a pre-defined chart type",
            "  - Pros: fast, easy, no coding needed",
            "  - Cons: limited customisation, may not fit",
            "    unusual data",
            "",
            'Component architecture ("build your own"):',
            "  - Construct visuals from primitives",
            "  - Pros: full control, any design possible",
            "  - Cons: requires programming, slower to produce",
            "",
            "Evaluation considers both:",
            "  Usability: how easy is the tool to use?",
            "  Utility: does the visualisation effectively",
            "  communicate the data?",
          ],
        },
        {
          id: 4,
          name: "Chernoff_faces_and_table_lens",
          title: "Chernoff Faces & Table Lens",
          category: "Multivariate Visualisation",
          file: "Chernoff_faces_and_table_lens.pdf",
          description: "Chernoff face examples and Table Lens visual mapping of quantitative values to bars.",
          content: [
            "Chernoff faces: each data row becomes a cartoon",
            "face.",
            "  - Variables mapped to facial features: face",
            "    width, eye size, eyebrow slant, nose length,",
            "    mouth shape, etc.",
            "  - Humans are naturally attuned to face",
            "    recognition, making differences noticeable",
            "  - Limitations: arbitrary feature mapping, can",
            "    be misleading, limited to ~15 variables",
            "",
            "Table Lens: interactive focus+context table.",
            "  - Quantitative values shown as horizontal bars",
            "    within table cells",
            "  - Users expand rows/columns of interest while",
            "    seeing the full dataset in context",
            "  - Combines detail and overview in one display",
          ],
        },
        {
          id: 5,
          name: "Mosaic_plot",
          title: "Mosaic Plot",
          category: "Multivariate Visualisation",
          file: "Mosaic_plot.pdf",
          description: "Mosaic plots for displaying proportions across categorical variables with nested rectangles.",
          content: [
            "Mosaic plots display proportions across",
            "categorical variables.",
            "  - Plot area recursively divided into nested",
            "    rectangles",
            "  - Width represents proportion of one variable",
            "  - Height represents proportion of a second",
            "    variable within that group",
            "  - Colour can encode a third variable or",
            "    highlight deviations from independence",
            "",
            "Useful for exploring relationships in",
            "contingency tables.",
            "  - Area of each tile is proportional to the",
            "    frequency of that combination",
            "  - Easy to spot over/under-represented",
            "    category combinations",
          ],
        },
        {
          id: 6,
          name: "Parallel_coordinates",
          title: "Parallel Coordinates",
          category: "Multivariate Visualisation",
          file: "Parallel_coordinates.pdf",
          description: "Parallel coordinate plots: variables along horizontal axis, data points as polylines across vertical axes.",
          content: [
            "Parallel coordinates: variables arranged as",
            "parallel vertical axes.",
            "  - Each data item is a polyline connecting its",
            "    values across all axes",
            "",
            "Patterns:",
            "  - Correlated variables: similar line slopes",
            "    between adjacent axes",
            "  - Crossing lines indicate inverse relationships",
            "  - Clusters appear as bundles of similar polylines",
            "",
            "  - Axis ordering matters: can reveal or hide",
            "    patterns",
            "  - Interactive brushing: select a range on one",
            "    axis to highlight matching lines",
            "  - Scales well to many variables; less well to",
            "    many data items (overplotting)",
          ],
        },
        {
          id: 7,
          name: "Meta_evaluation_approach",
          title: "Meta-Evaluation Approach",
          category: "Evaluation",
          file: "Meta_evaluation_approach.pdf",
          description: "Desirable evaluation features: generalisability, precision, realism; methodologies vs features.",
          content: [
            "Desirable features when evaluating visualisation",
            "tools:",
            "",
            "  Generalisability: results apply beyond the",
            "    specific test case",
            "  Precision: results are quantitatively",
            "    measurable and reproducible",
            "  Realism: evaluation reflects real-world usage",
            "",
            "No single method scores high on all three;",
            "there is always a trade-off.",
            "",
            "  Lab experiments: high precision, low realism",
            "  Field studies: high realism, lower precision",
            "  Heuristic evaluation: quick but less",
            "    generalisable",
            "",
            "Choose methodology based on which features",
            "matter most for the evaluation goal.",
          ],
        },
        {
          id: 8,
          name: "Quality_methods",
          title: "Quality Methods",
          category: "Evaluation",
          file: "Quality_methods.pdf",
          description: "Nested methods (observation, think-aloud), inspector evaluation (heuristics), observational context, FN dialogue.",
          content: [
            "Evaluation methods for visualisation quality:",
            "",
            "Observation: watch users interact with the",
            "  visualisation in context.",
            "",
            "Think-aloud: users verbalise their thought",
            "  process during tasks.",
            "  - Provides rich qualitative data about",
            "    usability issues",
            "",
            "Inspector (heuristic) evaluation: experts",
            "  assess against known usability principles.",
            "  - Fast and cheap but depends on expert quality",
            "",
            "Observation in context: naturalistic study in",
            "  real work environments.",
            "",
            "FN dialogue (Focus-group Narrative): facilitated",
            "  group discussions. Captures diverse perspectives",
            "  and use cases.",
          ],
        },
        {
          id: 9,
          name: "Evaluation_approach_and_exploration",
          title: "Evaluation Approach & Exploration Styles",
          category: "Evaluation",
          file: "Evaluation_approach_and_exploration.pdf",
          description: "Participant factors, fluid exploration styles, performance metrics, and evaluation challenges.",
          content: [
            "Participant factors affect evaluation outcomes:",
            "  expertise, domain knowledge, motivation.",
            "",
            "Fluid exploration styles:",
            "  - Systematic: structured, methodical approach",
            "  - Opportunistic: follow interesting leads",
            "  - Users explore differently depending on goals",
            "    and experience",
            "",
            "Performance metrics for evaluation:",
            "  - Task completion time",
            "  - Accuracy",
            "  - Error rate",
            "  - Satisfaction",
            "",
            "Challenges: measuring insight is hard; task-based",
            "metrics may miss real-world value. Longitudinal",
            "studies capture learning effects but are expensive.",
          ],
        },
        {
          id: 10,
          name: "Controlled_experiments",
          title: "Controlled Experiments",
          category: "Evaluation",
          file: "Controlled_experiments.pdf",
          description: "Quantitative evaluation: hypothesis, independent/dependent variables, control vs experimental groups.",
          content: [
            "Controlled experiments: the gold standard for",
            "quantitative evaluation.",
            "",
            "  Hypothesis: a testable prediction (e.g.",
            '    "Chart A leads to faster task completion")',
            "  Independent variable: what is manipulated",
            "    (e.g. chart type)",
            "  Dependent variable: what is measured",
            "    (e.g. time, accuracy)",
            "",
            "  Control group: baseline condition",
            "  Experimental group: new condition",
            "",
            "Designs:",
            "  Between-subjects: each participant uses one",
            "  Within-subjects: each uses all (counterbalanced)",
            "",
            "Statistical significance testing (p-values,",
            "confidence intervals) determines if differences",
            "are real. High precision but lower ecological",
            "validity.",
          ],
        },
      ],
    },
  ],
};

export default data_visualisation;
